function(GPS_default_assemble_rule target)
    set(inputVar "-mcpu=33FJ128GP310;-g;-DXPRJ_default=default;-Wa,--defsym=__MPLAB_BUILD=1,--no-relax,;-mdfp=C:/Users/fedyu/.mchp_packs/Microchip/dsPIC33F-GP-MC_DFP/1.4.235/xc16")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(GPS_default_assemblePreproc_rule target)
    set(inputVar "-mcpu=33FJ128GP310;-g;-DXPRJ_default=default;-Wa,--defsym=__MPLAB_BUILD=1,--no-relax,;-mdfp=C:/Users/fedyu/.mchp_packs/Microchip/dsPIC33F-GP-MC_DFP/1.4.235/xc16")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(GPS_default_compile_rule target)
    set(inputVar "-mcpu=33FJ128GP310;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};${COMPILER_STACK};-g;-DXPRJ_default=default;-O0;-msmart-io=1;-Wall;-msfr-warn=off;${INLINE_OVERRIDE};-mdfp=C:/Users/fedyu/.mchp_packs/Microchip/dsPIC33F-GP-MC_DFP/1.4.235/xc16")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(GPS_default_link_rule target)
    set(inputVar "-mcpu=33FJ128GP310;${INSTRUMENTED_TRACE_OPTIONS};${PC_SAMPLING_PROFILING_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-g;-DXPRJ_default=default;-Wl,--script=p33FJ128GP310.gld,--local-stack,${PRESERVE_FILE},--defsym=__MPLAB_BUILD=1,${MP_LINKER_FILE_OPTION},--stack=16,,--check-sections,,--data-init,,--pack-data,,--handles,,--isr,,--no-gc-sections,,--fill-upper=0,,--stackguard=16,,--no-force-link,,--smart-io,,--report-mem,,--memorysummary,memoryfile.xml;-mdfp=C:/Users/fedyu/.mchp_packs/Microchip/dsPIC33F-GP-MC_DFP/1.4.235/xc16")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
